# thymeleaf
spring:
  profiles:
    include: secret
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/samsaradb?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: q1w2e3r4t5
    driver-class-name: com.mysql.cj.jdbc.Driver 
  mvc:
    static-path-pattern: "/static/**"
mybatis:
  mapper-locations:
  - classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match: /**
  

  