Project Book_Management {
  database_type: 'MySQL'
  Note: '''
    # Book Management Database
    **도서관리시스템을 위한 DB설계**
  '''
}
Table member {
  user_id int [pk, increment]
  id varchar
  password varchar
  name varchar
  email varchar
  postcode varchar
  address varchar
  detailAddr varchar
  extraAddr varchar
  role_idx int
  borrowlimit int
  borrowCount int
  overdueCount int
  mannerCount int
  created_at datetime
  modifed_at datetime
  isLocked boolean
  isBlocked boolean
  isWithdraw boolean
  note: "table 'users' contains user information"
}
Table role {
  role_idx int
  permission_idx int
  roleName varchar
}
Table permission {
  permission_idx int
  board_idx int
  create boolean
  read boolean
  update boolean
  delete boolean
}
Table withdraw {
  id int
  user_idx int
  user_id varchar
  created_at
  state varchar
}
Table book {
  book_id int [pk]
  book_info int [fk]
  control_no varchar [note: "도서번호"]
  call_no varchar [note: "청구기호"]
  class_no varchar [note: "분류기호"]
  author_no varchar [note: "저자기호"]
  volume varchar [note: "권차"]
  copy varchar [note: "복본"]
  kdc varchar
  ddc varchar
  attachment varchar
  location_idx int
  keyword varchar
  created_at datetime [default: `now()`, note: "created time"]
  modified_at datetime [default: `now()`, note: "modified time"]
  note: "table 'books' contains book information"
}
Table location {
  location_idx int [pk]
  location_name varchar
}
Table book_manage {
  book_manage_id int [pk]
  type varchar
  description varchar
  purchase_at datetime
  created_at datetime
}
Table product {
  product_id int [pk]
  title varchar
  author varchar
  publisher varchar
  pubdate date
  isbn varchar
  edtion varchar
  volume varchar
  series varchar
  description varchar
  price varchar
  discount varchar
  purchase_price varchar 
  imgUrl varchar
  thumbUrl varchar
  created_at datetime [default: `now()`, note: "created time"]
  modified_at datetime [default: `now()`, note: "modified time"]
}
Table borrow {
  id int [pk]
  user_id int
  book_id int
  created_at datetime
  modifed_at datetime
  recieved_at datetime
}



